### ISSUE TITLE
September 2022 Feature Sprint - Progress

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/winutil#116]
### Requested Features

- [x] Remove Cortana Option #111 
- [ ] Clarify Auto-Download Driver installs #115 
- [ ] Add Option for Proxy users #106 
- [x] Add Viber for Desktop for Install #102 
- [ ] Debloat HP Analytics #100 
- [x] Add Dark Mode toggle #58 
- [x] Add Simplewall for Install #56 
- [ ] Fix Spotify Install by deescalating to user. #55 
- [x] Add WizTree for Install #42 
- [x] Add KDENLive Video Editor for Install #38 
- [x] Disable all Notifications option #23

**Comment by thetredev** [comment]
How about the Projects tab? :)

**Comment by SteffenCarlsen** [comment]
Regarding #106 - As long as the user has access to the github repository in some fashion, an alternative approach for running winutil could be proposed in the README. As in, manually downloading the powershell file/saving the source and running it that way.

**Comment by devinscodex** [comment]
Not sure how much interest there has been to add a "clear start menu" toggle on the tweaks page.  But below is the script that I normally run to perform it:

```powershell

function clearStartMenu {
		
# Requires -RunAsAdministrator

$START_MENU_LAYOUT = @"
<LayoutModificationTemplate xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" Version="1" xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
    <LayoutOptions StartTileGroupCellWidth="6" />
    <DefaultLayoutOverride>
        <StartLayoutCollection>
            <defaultlayout:StartLayout GroupCellWidth="6" />
        </StartLayoutCollection>
    </DefaultLayoutOverride>
</LayoutModificationTemplate>
"@

$layoutFile="C:\Windows\StartMenuLayout.xml"

#Delete layout file if it already exists
If(Test-Path $layoutFile)
{
    Remove-Item $layoutFile
}

#Creates the blank layout file
$START_MENU_LAYOUT | Out-File $layoutFile -Encoding ASCII

$regAliases = @("HKLM", "HKCU")

#Assign the start layout and force it to apply with "LockedStartLayout" at both the machine and user level
foreach ($regAlias in $regAliases){
    $basePath = $regAlias + ":\SOFTWARE\Policies\Microsoft\Windows"
    $keyPath = $basePath + "\Explorer" 
    IF(!(Test-Path -Path $keyPath)) { 
        New-Item -Path $basePath -Name "Explorer"
    }
    Set-ItemProperty -Path $keyPath -Name "LockedStartLayout" -Value 1
    Set-ItemProperty -Path $keyPath -Name "StartLayoutFile" -Value $layoutFile
}

#Restart Explorer, open the start menu (necessary to load the new layout), and give it a few seconds to process
Stop-Process -name explorer
Start-Sleep -s 5
$wshell = New-Object -ComObject wscript.shell; $wshell.SendKeys('^{ESCAPE}')
Start-Sleep -s 5

#Enable the ability to pin items again by disabling "LockedStartLayout"
foreach ($regAlias in $regAliases){
    $basePath = $regAlias + ":\SOFTWARE\Policies\Microsoft\Windows"
    $keyPath = $basePath + "\Explorer" 
    Set-ItemProperty -Path $keyPath -Name "LockedStartLayout" -Value 0
}

#Restart Explorer and delete the layout file
Stop-Process -name explorer

# Uncomment the next line to make clean start menu default for all new users
#Import-StartLayout -LayoutPath $layoutFile -MountPath $env:SystemDrive\

Remove-Item $layoutFile
}

clearStartMenu

```

**Comment by SteffenCarlsen** [comment]
@ChrisTitusTech In my now closed PR, we spoke about adding .NET install through winget. Microsoft just added this blog post about their official support of .NET installations through winget.

https://devblogs.microsoft.com/dotnet/dotnet-now-on-windows-package-manager/

**Comment by ChrisTitusTech** [comment]
Finished merging most of the feature sprint in #240. I'm going to push the rest into the next one and add some of the other options mentioned here.

**Comment by ChrisTitusTech** [comment]
Closing this and making new sprint for the fall.
