### ISSUE TITLE
Tracking List of MicroWin Discoverd/Reported Bugs

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#1664]
## Why create this list?
This list is meant to Track down all of MicroWin reported Issues, Bugs, and Un-expected Behaviors.
**Note**: This list will be updated regularly, so everyone can have a good idea of what have been reported and/or solved.

## All Open Reported Issues Since List Creation

- [ ] MicroWin Windows 10 Install.wim Issue
**source**: #1232 

- [ ] GPU usage is high during GUI open
**Duplicated Issue(s)**:
#1441
#1628
**source**: #1423
**Pull Request**: _Waiting for review..._ #1643

- [ ] Microwin creation successful, but no ISO file
**source**: #1592

- [ ] Still Getting Defender Notifications
**source**: #1616

- [ ] Wifi not showing
**source**: #1634

- [ ] Microwin: remove hardware requierments from the windows 11 ISO
**Duplicated Issue(s)**: #1308
**source**: #1637

**Comment by blusewill** [comment]
In 
`GPU usage is high during GUI open`
The Source is actually #1441
Others are duplicate since that issues opens first

**Comment by og-mrk** [comment]
Removed `GPU usage is high during GUI open` from the list, as it's an Issue related to WinUtil's GUI, and not MicroWin itself.

**Comment by og-mrk** [comment]
@ChrisTitusTech 
Request to keep this issue ticket open, in the case of it being helpful/informative to new/old contributors (the goal of this list).
